name: MacOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  wine-staging:
    # https://github.com/actions/runner-images/issues/9741
    runs-on:  macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install --cask xquartz
          brew install  autoconf \
                        bison \
                        gphoto2 \
                        gstreamer \
                        gcenx/wine/libinotify-kqueue \
                        mingw-w64 \
                        molten-vk \
                        sdl2

      - name: Add bison & krb5 to $PATH
        run: |
          set -eu
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix krb5)/bin" >> $GITHUB_PATH

      - name: Get upstream-commit
        run: |
          mkdir $GITHUB_WORKSPACE/wine
          cd wine
          git init
          git fetch https://gitlab.winehq.org/wine/wine.git $($GITHUB_WORKSPACE/staging/patchinstall.py --upstream-commit) --depth=1
          git checkout $($GITHUB_WORKSPACE/staging/patchinstall.py --upstream-commit)

      - name: Run patchinstall.py --all
        run: |
          cd wine
          $GITHUB_WORKSPACE/staging/patchinstall.py DESTDIR=. --all

      - name: Configure wine64
        env:
          LDFLAGS: "-Wl,-rpath,/opt/X11/lib"
          # Avoid weird linker errors with Xcode 10 and later
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure   --enable-win64 \
                        --without-alsa \
                        --without-capi \
                        --without-dbus \
                        --without-oss \
                        --without-pulse \
                        --without-udev \
                        --without-v4l2 \
                        --x-include=/opt/X11/include \
                        --x-lib=/opt/X11/lib

      - name: Build wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
